[tool.poetry]
name = "ripley-scraper"
version = "0.1.0"
description = ""
authors = ["juanj72TC <juan.jara@teamcore.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
